name: CI/CD Pipeline

on:
  push:
    branches: [ "Master" ]

jobs:
  delivey:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        host: 159.65.126.226
        port: 22
        script: |
          cd /home/cv-virtual && git pull
    - name: Send Telegram notification on pipeline completion
      uses: appleboy/telegram-action@master
      with:
        to: '1238026457'
        token: '6256198041:AAGrQsJDQ2vvSckyhkP1p1J7i8VJmfC_ebU'
        message: 'Pipeline completed successfully (cv-virtual).'
